### ISSUE TITLE
Vignette re-organization

### ISSUE THREAD

**Issue by rudeboybert** [rudeboybert/fivethirtyeight#21]
Some vignette reorganization:

1. Add a vignette that has a link to all user-contributed vignettes, which are only available on dev version of package and on GitHub due to CRAN package size restrictions.
1. For all datasets that have a user contributed vignette, add a link to it in the corresponding help/roxygen code file.

**Comment by ismayc** [comment]
Vignettes should link to Articles on http://fivethirtyeight-r.netlify.com/, right?

**Comment by rudeboybert** [comment]
I think that would work. As long as there is a "one-click" mechanism to get at:
1. a rendered html of the vignette
1. the Rmd source code

I think the approach doesn't matter.

**Comment by ismayc** [comment]
- [x] Add a vignette that has a link to all user-contributed vignettes, which are only available on dev version of package and on GitHub due to CRAN package size restrictions.
- [x] For all datasets that have a user contributed vignette, add a link to it in the corresponding help/roxygen code file.
- [x] Removed user-contributed vignettes from `vignettes` folder on `release` branch.

Further details on additions are at https://github.com/rudeboybert/fivethirtyeight/compare/release

**Comment by rudeboybert** [comment]
sweeeeet. thanks
